version: '3'

services:
  redis-master:
    image: bitnami/redis:7.4
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '6379:6379'

  redis-replica-1:
    image: bitnami/redis:7.4
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - redis-master

  redis-replica-2:
    image: bitnami/redis:7.4
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - redis-master

  sentinel-1:
    image: bitnami/redis-sentinel:7.4
    ports:
      - '26379:26379'
    environment:
      REDIS_SENTINEL_QUORUM: '2'
      REDIS_MASTER_NAME: mymaster
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT_NUMBER: '6379'
      ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2

  sentinel-2:
    image: bitnami/redis-sentinel:7.4
    environment:
      REDIS_SENTINEL_QUORUM: '2'
      REDIS_MASTER_NAME: mymaster
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT_NUMBER: '6379'
      ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - redis-master

  sentinel-3:
    image: bitnami/redis-sentinel:7.4
    environment:
      REDIS_SENTINEL_QUORUM: '2'
      REDIS_MASTER_NAME: mymaster
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT_NUMBER: '6379'
      ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - redis-master
